/**
 * Bollywood Songs Playlist
 * Curated for the Indian Delivery Boys web app
 */

const SONGS = [
  // 90s Classics (30+ songs)
  { id: 1, title: 'Tujhe Dekha Toh Yeh Jaana Sanam', artist: 'Kumar Sanu, Lata Mangeshkar', movie: 'DDLJ', year: 1995, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
  { id: 2, title: 'Pehla Nasha', artist: 'Udit Narayan', movie: 'Jo Jeeta Wohi Sikandar', year: 1992, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3' },
  { id: 3, title: 'Chaiyya Chaiyya', artist: 'Sukhwinder Singh', movie: 'Dil Se', year: 1998, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3' },
  { id: 4, title: 'Kuch Kuch Hota Hai', artist: 'Udit Narayan, Alka Yagnik', movie: 'KKHH', year: 1998, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3' },
  { id: 5, title: 'Ek Ladki Ko Dekha', artist: 'Kumar Sanu', movie: '1942: A Love Story', year: 1994, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3' },
  { id: 6, title: 'Dil To Pagal Hai', artist: 'Lata Mangeshkar, Udit Narayan', movie: 'Dil To Pagal Hai', year: 1997, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3' },
  { id: 7, title: 'Jaadu Teri Nazar', artist: 'Udit Narayan', movie: 'Darr', year: 1993, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg' },
  { id: 8, title: 'Ye Kaali Kaali Aankhen', artist: 'Kumar Sanu', movie: 'Baazigar', year: 1993, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
  { id: 9, title: 'Tu Mile Dil Khile', artist: 'Kumar Sanu', movie: 'Criminal', year: 1994, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3' },
  { id: 10, title: 'Mere Sapno Ki Rani', artist: 'Kishore Kumar', movie: 'Aradhana', year: 1969, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3' },
  { id: 11, title: 'Papa Kehte Hain', artist: 'Udit Narayan', movie: 'QSQT', year: 1988, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3' },
  { id: 12, title: 'Ae Mere Humsafar', artist: 'Udit Narayan, Alka Yagnik', movie: 'QSQT', year: 1988, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3' },
  { id: 13, title: 'Dil Hai Ki Manta Nahin', artist: 'Kumar Sanu, Anuradha Paudwal', movie: 'Dil Hai Ki Manta Nahin', year: 1991, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3' },
  { id: 14, title: 'Dekha Hai Pehli Baar', artist: 'Kumar Sanu', movie: 'Saajan', year: 1991, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg' },
  { id: 15, title: 'Mera Dil Bhi Kitna Pagal Hai', artist: 'Kumar Sanu, Alka Yagnik', movie: 'Saajan', year: 1991, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
  { id: 16, title: 'Tip Tip Barsa Paani', artist: 'Alka Yagnik, Udit Narayan', movie: 'Mohra', year: 1994, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3' },
  { id: 17, title: 'Tu Cheez Badi Hai Mast Mast', artist: 'Udit Narayan', movie: 'Mohra', year: 1994, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3' },
  { id: 18, title: 'Chura Ke Dil Mera', artist: 'Kumar Sanu', movie: 'Main Khiladi Tu Anari', year: 1994, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3' },
  { id: 19, title: 'Sochenge Tumhe Pyar', artist: 'Kumar Sanu', movie: 'Deewana', year: 1992, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3' },
  { id: 20, title: 'Tere Naam', artist: 'Udit Narayan', movie: 'Tere Naam', year: 2003, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3' },
  { id: 21, title: 'Aashiqui Mein Har Aashiq', artist: 'Kumar Sanu', movie: 'Aashiqui', year: 1990, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg' },
  { id: 22, title: 'Nazar Ke Saamne', artist: 'Kumar Sanu', movie: 'Aashiqui', year: 1990, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
  { id: 23, title: 'Dheere Dheere Se', artist: 'Kumar Sanu', movie: 'Aashiqui', year: 1990, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3' },
  { id: 24, title: 'Pehli Pehli Baar Mohabbat Ki Hai', artist: 'Kumar Sanu', movie: 'Sirf Tum', year: 1999, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3' },
  { id: 25, title: 'Main Koi Aisa Geet Gaoon', artist: 'Kumar Sanu', movie: 'Yes Boss', year: 1997, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3' },
  { id: 26, title: 'Chand Sifarish', artist: 'Shaan', movie: 'Fanaa', year: 2006, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3' },
  { id: 27, title: 'Taal Se Taal Mila', artist: 'A.R. Rahman', movie: 'Taal', year: 1999, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3' },
  { id: 28, title: 'Rang De Basanti', artist: 'Daler Mehndi', movie: 'Rang De Basanti', year: 2006, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg' },
  { id: 29, title: 'Sandese Aate Hain', artist: 'Sonu Nigam, Roop Kumar Rathod', movie: 'Border', year: 1997, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
  { id: 30, title: 'Hum Tumhare Hain Sanam', artist: 'S.P. Balasubrahmanyam', movie: 'HAHK', year: 1994, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3' },
  { id: 31, title: 'Didi Tera Devar Deewana', artist: 'Lata Mangeshkar, S.P. Balasubrahmanyam', movie: 'HAHK', year: 1994, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3' },

  // 2000s Hits (25+ songs)
  { id: 32, title: 'Kal Ho Naa Ho', artist: 'Sonu Nigam', movie: 'KHNH', year: 2003, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3' },
  { id: 33, title: 'Kajra Re', artist: 'Alisha Chinai, Shankar Mahadevan', movie: 'Bunty Aur Babli', year: 2005, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3' },
  { id: 34, title: 'Tum Se Hi', artist: 'Mohit Chauhan', movie: 'Jab We Met', year: 2007, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3' },
  { id: 35, title: 'Mauja Hi Mauja', artist: 'Mika Singh', movie: 'Jab We Met', year: 2007, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg' },
  { id: 36, title: 'Tera Hone Laga Hoon', artist: 'Atif Aslam', movie: 'Ajab Prem Ki Ghazab Kahani', year: 2009, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
  { id: 37, title: 'Dil Chahta Hai', artist: 'Shankar Mahadevan', movie: 'DCH', year: 2001, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3' },
  { id: 38, title: 'Jaane Kyun', artist: 'Zubin', movie: 'Dostana', year: 2008, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3' },
  { id: 39, title: 'Kya Mujhe Pyaar Hai', artist: 'KK', movie: 'Woh Lamhe', year: 2006, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3' },
  { id: 40, title: 'Tadap Tadap', artist: 'KK', movie: 'Hum Dil De Chuke Sanam', year: 1999, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3' },
  { id: 41, title: 'Dola Re Dola', artist: 'Kavita Krishnamurthy, Shreya Ghoshal', movie: 'Devdas', year: 2002, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3' },
  { id: 42, title: 'Dil Se Re', artist: 'A.R. Rahman', movie: 'Dil Se', year: 1998, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg' },
  { id: 43, title: 'Zara Sa Jhoom Loon Main', artist: 'Asha Bhosle', movie: 'DDLJ', year: 1995, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
  { id: 44, title: 'Senorita', artist: 'Shankar, Loy', movie: 'Zindagi Na Milegi Dobara', year: 2011, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3' },
  { id: 45, title: 'Bheegi Bheegi Raaton Mein', artist: 'Adnan Sami', movie: 'Ajnabee', year: 2001, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3' },
  { id: 46, title: 'Do Pal', artist: 'Lata Mangeshkar, Sonu Nigam', movie: 'Veer-Zaara', year: 2004, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3' },
  { id: 47, title: 'Main Yahaan Hoon', artist: 'Udit Narayan', movie: 'Veer-Zaara', year: 2004, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3' },
  { id: 48, title: 'Phir Le Aya Dil', artist: 'Arijit Singh', movie: 'Barfi', year: 2012, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3' },
  { id: 49, title: 'Tum Hi Ho', artist: 'Arijit Singh', movie: 'Aashiqui 2', year: 2013, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg' },
  { id: 50, title: 'Kun Faya Kun', artist: 'A.R. Rahman, Javed Ali', movie: 'Rockstar', year: 2011, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
  { id: 51, title: 'Tujhe Bhula Diya', artist: 'Mohit Chauhan', movie: 'Anjaana Anjaani', year: 2010, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3' },
  { id: 52, title: 'Kabhi Alvida Naa Kehna', artist: 'Sonu Nigam', movie: 'KANK', year: 2006, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3' },
  { id: 53, title: 'Maahi Ve', artist: 'Faakhir', movie: 'Kaante', year: 2002, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3' },
  { id: 54, title: 'Kaho Naa Pyaar Hai', artist: 'Udit Narayan', movie: 'KNPH', year: 2000, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3' },
  { id: 55, title: 'Tera Mera Rishta', artist: 'Kumar Sanu, Alka Yagnik', movie: 'Awarapan', year: 2007, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3' },

  // Modern Hits (24+ songs)
  { id: 56, title: 'Tum Hi Ho (Reprise)', artist: 'Arijit Singh', movie: 'Aashiqui 2', year: 2013, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg' },
  { id: 57, title: 'Tera Ban Jaunga', artist: 'Akhil Sachdeva, Tulsi Kumar', movie: 'Kabir Singh', year: 2019, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
  { id: 58, title: 'Tujhe Kitna Chahne Lage', artist: 'Arijit Singh', movie: 'Kabir Singh', year: 2019, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3' },
  { id: 59, title: 'Dil Diyan Gallan', artist: 'Atif Aslam', movie: 'Tiger Zinda Hai', year: 2017, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3' },
  { id: 60, title: 'Shayad', artist: 'Arijit Singh', movie: 'Love Aaj Kal', year: 2020, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3' },
  { id: 61, title: 'Hawayein', artist: 'Arijit Singh', movie: 'Jab Harry Met Sejal', year: 2017, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3' },
  { id: 62, title: 'Raabta', artist: 'Arijit Singh', movie: 'Agent Vinod', year: 2012, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3' },
  { id: 63, title: 'Channa Mereya', artist: 'Arijit Singh', movie: 'ADHM', year: 2016, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg' },
  { id: 64, title: 'Bulleya', artist: 'Amit Mishra', movie: 'ADHM', year: 2016, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
  { id: 65, title: 'Gerua', artist: 'Arijit Singh, Antara Mitra', movie: 'Dilwale', year: 2015, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3' },
  { id: 66, title: 'Jeena Jeena', artist: 'Atif Aslam', movie: 'Badlapur', year: 2015, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3' },
  { id: 67, title: 'Soch Na Sake', artist: 'Arijit Singh, Tulsi Kumar', movie: 'Airlift', year: 2016, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3' },
  { id: 68, title: 'Tera Yaar Hoon Main', artist: 'Arijit Singh', movie: 'Sonu Ke Titu Ki Sweety', year: 2018, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3' },
  { id: 69, title: 'Ik Vaari Aa', artist: 'Arijit Singh', movie: 'Raabta', year: 2017, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3' },
  { id: 70, title: 'Ve Maahi', artist: 'Arijit Singh, Asees Kaur', movie: 'Kesari', year: 2019, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg' },
  { id: 71, title: 'Lut Gaye', artist: 'Jubin Nautiyal', movie: 'Single', year: 2021, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
  { id: 72, title: 'Raataan Lambiyan', artist: 'Jubin Nautiyal, Asees Kaur', movie: 'Shershaah', year: 2021, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3' },
  { id: 73, title: 'Mann Bharryaa', artist: 'B Praak', movie: 'Shershaah', year: 2021, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3' },
  { id: 74, title: 'Ranjha', artist: 'B Praak', movie: 'Shershaah', year: 2021, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3' },
  { id: 75, title: 'Kesariya', artist: 'Arijit Singh', movie: 'Brahmastra', year: 2022, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3' },
  { id: 76, title: 'Pasoori', artist: 'Ali Sethi, Shae Gill', movie: 'Coke Studio', year: 2022, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3' },
  { id: 77, title: 'Apna Bana Le', artist: 'Arijit Singh', movie: 'Bhediya', year: 2022, audioUrl: 'https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg' },
  { id: 78, title: 'Phir Aur Kya Chahiye', artist: 'Arijit Singh', movie: 'Zara Hatke Zara Bachke', year: 2023, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
  { id: 79, title: 'O Maahi', artist: 'Arijit Singh', movie: 'Dunki', year: 2023, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3' },
  { id: 80, title: 'Heeriye', artist: 'Jasleen Royal, Arijit Singh', movie: 'Single', year: 2023, audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3' }
];

const SONG_CATEGORIES = {
  romantic: [1, 2, 4, 5, 6, 7, 9, 10, 12, 13, 14, 15, 19, 21, 22, 23, 24, 25, 26, 30, 32, 34, 36, 39, 46, 47, 49, 56, 57, 58, 59, 60, 61, 62, 63, 65, 66, 67, 68, 69, 70, 72, 74, 75, 77, 78, 79, 80],
  sad: [20, 40, 48, 51, 52, 63, 73],
  upbeat: [3, 8, 11, 17, 18, 28, 31, 33, 35, 37, 38, 41, 43, 44, 45, 50, 53, 54, 64, 71, 76],
  rain: [16, 27, 42, 45]
};

